IF(OBJECT_ID('FK_MeetupId', 'F') IS NOT NULL)
BEGIN
	ALTER TABLE [dbo].[MeetupMembersRsvp] DROP CONSTRAINT FK_MeetupId;
END

IF(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'Meetup'))
BEGIN
	DROP TABLE [dbo].[Meetup]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Meetup](
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Group] VARCHAR(255) UNIQUE NOT NULL,
	[CreatedOn] DATETIME NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


