IF(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'Members'))
BEGIN
	DROP TABLE [dbo].[Members]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Members](
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[UserName] VARCHAR(255) UNIQUE NOT NULL,
	[Role] VARCHAR(255) UNIQUE NOT NULL,
	[IsFrozen] BIT NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


