IF(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'Roles'))
BEGIN
	DROP TABLE [dbo].[Roles]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Roles](
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[MemberId] INT NOT NULL CONSTRAINT FK_UserRoles FOREIGN KEY REFERENCES [Members]([Id]) ON DELETE CASCADE,
	[Name] VARCHAR(200) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


