IF(EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'UserClaims'))
BEGIN
	DROP TABLE [dbo].[UserClaims]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserClaims](
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[UserId] INT NOT NULL CONSTRAINT FK_UserClaims FOREIGN KEY REFERENCES [User]([Id]) ON DELETE CASCADE,
	[Type] VARCHAR(200) NOT NULL,
	[Value] VARCHAR(max) NOT NULL,
	[ValueType] VARCHAR(255) NULL DEFAULT('http://www.w3.org/2001/XMLSchema#string'),
	[Issuer] VARCHAR(255) NULL DEFAULT('Custom Authority')
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


